### ISSUE TITLE
Burp binary doesn't seems to come with ncurses compiled with

### ISSUE THREAD

**Issue by neo-inuit** [CoffeeITWorks/ansible_burp2_server#12] opened 2017-06-21 16:08 UTC
Hello,

I used to install my backup server with your burp2 recipe and everything is going well, but it seems that when i want to use the classic burp command below : 

`burp -c /etc/burp/burp-server.conf -a S`

It seems that ncurses was not added to the burp compilation, that's the normal behaviour ?

Thanks for the answer.

**Comment by pablodav** [comment] 2017-06-22 00:31
Seems that you didn't notice that burp 2.x changed the way it shows the ncurses and client interface. 

You need a client connected to burp-server since 2.x, and use the client to see the ncurses or any client operation like new json api. 

fortunately this role does all the setup required for you! 

so you only need to use: 

    burp -c /etc/burp/burp.conf -a s 

as the role by default also adds the client as `restore_client`, it will see also all clients on the server (not just the `monitor` itself). 

https://github.com/CoffeeITWorks/ansible_burp2_server/blob/master/defaults/main.yml#L297

```yaml
burp_restore_clients:
  - monitor
```

This role also has a var to activate config for `burpui-agent`

```yaml
# Configure Burp UI Agent
burp_module_agent: false
```
also creates a specific client for it. 

client setup is done by task: 

https://github.com/CoffeeITWorks/ansible_burp2_server/blob/master/tasks/local_client.yml

Docs about status monitor: 

http://burp.grke.org/docs/monitor.html

About other roles built over burp, burpui, burp_reports: 

https://github.com/grke/burp/wiki/automated-deploy-and-maintenance 

Hope this will resolve your issue. 

You are welcome to ask anything else!

**Comment by pablodav** [comment] 2017-06-26 00:19
hello @neo-inuit did you check it? does it solves the issue?

**Comment by neo-inuit** [comment] 2017-06-29 14:53
Hi @pablodav , thanks for your detailed answer, that's solved my issue and i am able to see all my backup jobs. After a little delay the command doesn't work anymore and i have to restart burp-server, to be able to use the command again. I have maybe something broken with my setup, i will try to fix it later. thanks

**Comment by pablodav** [comment] 2017-06-30 18:12
Sounds strange for me, I haven't tried myself debian 9 but I'm sure it is working because it passes automatic testing with latest debian and also @pilasguru tested it as reported in https://github.com/CoffeeITWorks/ansible_burp2_client/issues/2 

In my case I'm using this role in production with 5 ubuntu 14.04 servers and 400 clients with no issues like this. 

maybe you can pass more details about the issue you have now and will try to help you on that.

**Comment by pablodav** [comment] 2017-07-05 12:21
Hello @neo-inuit 

can I help in something else?

**Comment by pablodav** [comment] 2017-08-24 00:11
Hello @neo-inuit I will close it as seems the problem is solved and no answer is received. 

I'm will be pleased to help on any other issue.

**Closed by pablodav** 2017-08-24 00:11 UTC
Labels: help wanted, invalid
